language: rust
rust:
  - stable
matrix:
  fast_finish: true

script:
  - cargo build --verbose --all

after_success:
  - ./after-success.sh
  
# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work
#cache:
#  directories:
#    - /home/travis/.cargo

# But don't cache the cargo registry
#before_cache:
#  - rm -rf /home/travis/.cargo/registry

